{"level": "INFO", "message": "start aiohttp application", "timestamp": "2024-07-29T19:27:25.491522+00:00", "logger": "app.aiohttp_application", "module": "aiohttp_application", "function": "__init__", "line": 8, "thread_name": "MainThread"}
{"level": "DEBUG", "message": "Using proactor: IocpProactor", "timestamp": "2024-07-29T19:27:25.492523+00:00", "logger": "asyncio", "module": "proactor_events", "function": "__init__", "line": 634, "thread_name": "MainThread"}
{"level": "INFO", "message": "start big_ship.litematic", "timestamp": "2024-07-29T19:27:29.703248+00:00", "logger": "app.handlers.get_optomized_litematic", "module": "get_optomized_litematic", "function": "get_optimized_litematic", "line": 23, "thread_name": "MainThread"}
{"level": "ERROR", "message": "Exception in callback BaseProactorEventLoop._start_serving.<locals>.loop(<_OverlappedF....68', 53479))>) at C:\\Users\\modecstap\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\proactor_events.py:841\nhandle: <Handle BaseProactorEventLoop._start_serving.<locals>.loop(<_OverlappedF....68', 53479))>) at C:\\Users\\modecstap\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\proactor_events.py:841>", "timestamp": "2024-07-29T19:28:18.592857+00:00", "logger": "asyncio", "module": "base_events", "function": "default_exception_handler", "line": 1785, "thread_name": "MainThread", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\modecstap\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\events.py\", line 84, in _run\n    self._context.run(self._callback, *self._args)\n  File \"C:\\Users\\modecstap\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\proactor_events.py\", line 856, in loop\n    self._make_socket_transport(\n  File \"C:\\Users\\modecstap\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\proactor_events.py\", line 647, in _make_socket_transport\n    return _ProactorSocketTransport(self, sock, protocol, waiter,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\modecstap\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\proactor_events.py\", line 613, in __init__\n    super().__init__(loop, sock, protocol, waiter, extra, server)\n  File \"C:\\Users\\modecstap\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\proactor_events.py\", line 189, in __init__\n    super().__init__(loop, sock, protocol, waiter, extra, server)\n  File \"C:\\Users\\modecstap\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\proactor_events.py\", line 335, in __init__\n    super().__init__(*args, **kw)\n  File \"C:\\Users\\modecstap\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\proactor_events.py\", line 66, in __init__\n    self._server._attach()\n  File \"C:\\Users\\modecstap\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 294, in _attach\n    assert self._sockets is not None\nAssertionError"}
